### PR TITLE
fix: IOS native review bad UX experience

### PR DESCRIPTION
**Pull request by regevbr**
fix: #279
fix: #278
fix: #267

@westonganger can you please review?

### CODE REVIEW

**Comment by westonganger** [comment]
**If InAppBrowser does NOT work for iOS**

Your saying InAppBrowser doesnt work for iOS? If so lets not include that option. We can simply default to the native app store review if `inAppReview: false` 

**If InAppBrowser does work on iOS**
Rather than adding another option why dont we unify them:

```javascript
iosReviewType: 'AppStoreReview' // default
iosReviewType: 'InAppReview'
iosReviewType: 'InAppBrowser'
```

**Comment by westonganger** [comment]
Maybe to future proof this we should change the syntax to:

```javascript
reviewType: {
  ios: 'AppStoreReview', // default
  ios: 'InAppReview',
  ios: 'InAppBrowser',
}
```

Please implement the above if you agree.

**Comment by regevbr** [comment]
sounds perfect will submit it soon

**Comment by regevbr** [comment]
@westonganger Already fixed typescript defentiions. About the change log, what is the version you want to give?

**Comment by westonganger** [comment]
Sorry I usually leave a section like the following:

- **Unreleased**
  * Nothing yet

Please use "Unreleased"

**Comment by regevbr** [comment]
Done please review

**Comment by westonganger** [comment]
Please fix the indentation in `www/AppRate.js` and if possible can you rebase to 1 commit? Ex. `git rebase -i HEAD~6`

Also please change the first changelog entry to: 

```
Removed iOS option `inAppReview` in favor of new option `reviewType`. Please update your app according to the updated documentation.
```

**Comment by regevbr** [comment]
Done. The indent issues were because I use tabs and in my display, they are equal to 2 spaces :-)

**Comment by westonganger** [comment]
Awesome great work. Thanks for your contribution!

**Comment by regevbr** [comment]
Thanks for helping with getting the fix through fast!
When can we expect a new version?

**Comment by westonganger** [comment]
Maybe in about a month. I like to let things percolate for a time before releasing.

**Comment by regevbr** [comment]
Ok I'll will update my plugin directly from github. Can you let me know why you need that time to wait? No one (well besides me) will be able to give feedback of the changes if they are not released and used...

**Pull request merged**
