### PR TITLE
Plugin and dependency ids fixed to new cordova plugin naming convention

### PR DESCRIPTION
**Pull request by mlegenhausen**
Solves #88 and please push to npm.

### CODE REVIEW

**Comment by ohh2ahh** [comment]
+1

**Comment by speige** [comment]
+1

**Comment by mlegenhausen** [comment]
We already use this version in production in an iOS and Android App.

**Comment by speige** [comment]
Yes, it works if you compile with an old version of PhoneGap/Cordova, I am
using it in production apps as well. Adobe made a breaking change in their
most recent version and the plugin no longer works if you compile against
the latest Phonegap/Cordova version.

On Tue, Sep 22, 2015 at 1:00 AM, Malte Legenhausen <notifications@github.com

**Comment by mlegenhausen** [comment]
I mean my pull request ;) Yes it does not work with the current version that why I provided one.

**Comment by speige** [comment]
My mistake. I sent an email to the users with commit permissions to this repository (fpmweb & PushAndPlay) asking them to merge this pull request into the main branch, I mistakenly thought the GitHub email I was replying to was from them. Sorry.

**Comment by mlegenhausen** [comment]
Thanks :)

**Comment by speige** [comment]
I uploaded a forked version to npm so PhoneGapBuild users (like me) can use this. I haven't tested it very well yet, if anyone wants to test it out & give feedback, feel free.

<gap:plugin name="cordova-plugin-apprate" source="npm" />

https://www.npmjs.com/package/cordova-plugin-apprate

It's a combination of both your & ohh2ahh's of pull requests. If you want commit access to the forked repo, let me know.

**Comment by mlegenhausen** [comment]
Commit access would be great. Then I don't have to fork always for little changes in the plugin.

**Pull request merged**
