### PR TITLE
Rename plugin dependencies to new naming model

### PR DESCRIPTION
**Pull request by ohh2ahh**
* cordova-plugin-dialogs
* cordova-plugin-globalization
* cordova-plugin-inappbrowser (Android only)

### CODE REVIEW

**Comment by zwacky** [comment]
+1

**Comment by speige** [comment]
+1

**Comment by speige** [comment]
I uploaded a forked version to npm so PhoneGapBuild users (like me) can use this. I haven't tested it very well yet, if anyone wants to test it out & give feedback, feel free.

<gap:plugin name="cordova-plugin-apprate" source="npm" />

https://www.npmjs.com/package/cordova-plugin-apprate

It's a combination of both your & mlegenhausen's pull requests. If you want commit access to the forked repo, let me know.

**Comment by westonganger** [comment]
Fixed in #78 and 1f7289c

**Pull request closed without merging**
