### PR TITLE
Fix error in IOS 17 in method launchAppStore

### PR DESCRIPTION
**Pull request by westonganger**
Solves #327 by wrapping the whole method in `dispatch_async(dispatch_get_main_queue(), ^{ do_the_stuff });`

Thanks to @jellomaster for suggesting the fix in the thread

### CODE REVIEW

**Comment by joelcook** [comment]
Question, what's the chances of this getting merged in the near future?

**Comment by jacobg** [comment]
Thanks! Will a new release version of this plugin be published?

**Comment by svt932** [comment]
Why not release it?

**Comment by westonganger** [comment]
v1.7.3 is now released with these ﻿changes

**Pull request merged**
