### PR TITLE
fix customLocale initial value

### PR DESCRIPTION
**Pull request by rei1011**
I think it would be better to modify the initial value of preferences.customLocale in AppRate.js to match the formatting with Index.d.ts.

At this time, setting customLocale in AppRate.setPreferences will likely result in customLocale = null.

@westonganger can you please review?

### CODE REVIEW

**Comment by westonganger** [comment]
`customLocale` should be null if its not explicitly set. Please clarify.

**Comment by rei1011** [comment]
@westonganger Thank you for confirming this.

At the moment, the initial value of preferences.customLocale is not of type object, so when setPreferences(pref[key], prefObj[key]) is executed recursively on line 229, the conditional expression on line 227 is false so preferences.customLocale will not be set.

Please check it out.

**Comment by westonganger** [comment]
Please fix the code at line 229 then.

**Comment by rei1011** [comment]
@westonganger  Thank you for confirming this.

The conditional expression in setPreferences has been changed.
Please check it out.

**Comment by westonganger** [comment]
Merged. Thanks for your contribution!

**Comment by EinfachHans** [comment]
I'm not sure if i understand that change. If the expression on line 227 is false, how can modifying line 229 help? Maybe i'm wrong, but with that change the `customLocale` object isn't updated recursively anymore, correct? So let's say i first call it with some values and then call it a second time it will completely override the values i have set in `customLocale` first?

**Pull request merged**
