### PR TITLE
Add support to SKStoreReviewController for In-App Reviews in iOS

### PR DESCRIPTION
**Pull request by jesusbotella**
Hello everyone!

I have added support to the new in-app rating system that Apple released for iOS 10.3 or above. I thought that it would be useful to make a PR, making it available in the plugin.

This new app reviewing feature is only available in iOS 10.3 or above. There is only one limitation, you only can ask for review three times a year.

Here you have the [SKStoreReviewController API Reference](https://developer.apple.com/reference/storekit/skstorereviewcontroller) and the [iOS Human Interface Guidelines](https://developer.apple.com/ios/human-interface-guidelines/interaction/ratings-and-reviews/) about Ratings and Reviews.

All feedback is welcomed, and I hope you like this PR.

### CODE REVIEW

**Comment by westonganger** [comment]
It looks like you replaced the original functionality with the new one so it wouldn't work on devices older than iOS 10.3. It should gracefully fallback to the open app store way if the device is older than iOS 10.3 and maybe it should also gracefully fallback when the 3 reviews limitation has been exceeded.

**Comment by jesusbotella** [comment]
No, I didn't replaced the original functionality with the new one.

If you look at [this method](https://github.com/jesusbotella/cordova-plugin-apprate/blob/97d0b74d6e8efcce2b02d33ab69cd6af245fc62b/src/ios/CDVAppRate.m#L44), I check if the new review method is available,  and if it is not, it has a fallback for older devices with the code that was executed before.

I didn't add a check for the three reviews yet, but it might be a good improvement.

**Comment by filipsuk** [comment]
It would be great to have this feature! I found two other plugins using it, however it would be nice to have it available in this all-in-one plugin.

- https://github.com/omaxlive/com.omarben.inappreview
- https://github.com/getsafe/cordova-plugin-requestreview

**Comment by westonganger** [comment]
@jesusbotella would love it if you could add the graceful fallback for once the 3 reviews limitation. Once thats done we can merge this PR.

**Comment by jesusbotella** [comment]
@westonganger Let's see if I can implement it this weekend, and updated in the PR ;)

**Comment by jesusbotella** [comment]
Hello again!

I have just uploaded the new feature to limit native rating prompt to three occurrences within a 365-day period. Give it a look, and if there is anything to change, please tell me and I'll fix it :)

**Comment by westonganger** [comment]
Looks great! Thanks for your hard work!

**Comment by jesusbotella** [comment]
@westonganger That was fast! Thank you so much!

**Comment by jesusbotella** [comment]
@westonganger Can you please give a bump to the version number, and publish it to npm?
I forgot to change it :(

**Comment by westonganger** [comment]
Please note that after merging this I have since changed the preference option `openStoreInApp` which defaults to false ----> `inAppReview` which defaults to true

As for the new version, I would like to let the changes sit and get tested for a little bit. Please use master for the time being.

**Comment by jesusbotella** [comment]
OK, no problem :)

I have tested it on my device but it is much better to be tested by more users of the plugin :)

**Comment by filipsuk** [comment]
It works for me. Just had to add some keys to my custom locale for some reason. I was getting errors from `Locales.getLocale` method on lines 56-62. I'm using the simple mode, so I don't need all the localizations. I just set them to empty strings and it works ok now.

**Comment by westonganger** [comment]
Can you tell me which keys you needed to add blanks on?

**Comment by filipsuk** [comment]
@westonganger I added these:
- appRatePromptTitle
- feedbackPromptTitle
- appRatePromptMessage
- feedbackPromptMessage

**Comment by westonganger** [comment]
Thanks. The latest master should now have this fixed.

**Pull request merged**
